"""
src/models.py
-------------
Pydantic data models for the FinAgent system.
Covers task lifecycle, agent steps, and API request/response schemas.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------


class TaskStatus(StrEnum):
    """Lifecycle states for a submitted task."""

    PENDING = "pending"
    PLANNING = "planning"
    EXECUTING = "executing"
    VERIFYING = "verifying"
    COMPLETED = "completed"
    FAILED = "failed"
    ESCALATED = "escalated"


class StepType(StrEnum):
    """Taxonomy of individual agent steps recorded in the task log."""

    PLAN = "plan"
    TOOL_CALL = "tool_call"
    OBSERVATION = "observation"
    VERIFICATION = "verification"
    ESCALATION = "escalation"
    RECOVERY = "recovery"


# ---------------------------------------------------------------------------
# Core data models
# ---------------------------------------------------------------------------


class AgentStep(BaseModel):
    """A single recorded action taken by the agent during task execution."""

    step_id: str = Field(
        default_factory=lambda: str(uuid.uuid4())[:8],
        description="Short unique identifier for this step.",
    )
    step_type: StepType
    description: str = Field(..., description="Human-readable summary of what this step did.")
    input: Any | None = Field(default=None, description="Input payload sent to the tool or LLM.")
    output: Any | None = Field(
        default=None, description="Raw output returned by the tool or LLM."
    )
    success: bool | None = Field(default=None, description="Whether this step succeeded.")
    error: str | None = Field(default=None, description="Error message if the step failed.")
    timestamp: datetime = Field(
        default_factory=datetime.utcnow,
        description="UTC timestamp when the step was executed.",
    )
    duration_ms: float | None = Field(
        default=None, description="Wall-clock duration of the step in milliseconds."
    )


class TaskState(BaseModel):
    """Full mutable state for a single FinAgent task from submission to completion."""

    task_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Globally unique task identifier.",
    )
    original_task: str = Field(..., description="The original natural-language task description.")
    status: TaskStatus = Field(default=TaskStatus.PENDING, description="Current lifecycle state.")

    # Planning
    plan: list[str] | None = Field(
        default=None, description="Ordered list of planned steps generated by the LLM."
    )

    # Execution history
    steps: list[AgentStep] = Field(
        default_factory=list,
        description="Chronological log of all agent steps taken.",
    )

    # Retry / escalation tracking
    retry_count: int = Field(
        default=0, description="Number of consecutive failures / retries encountered."
    )

    # Shared key-value store passed between steps (e.g. extracted invoice IDs)
    context: dict[str, Any] = Field(
        default_factory=dict,
        description="Shared execution context carrying data between steps.",
    )

    # Outcomes
    final_report: str | None = Field(
        default=None, description="Evidence-backed final report generated after task completion."
    )
    error_message: str | None = Field(
        default=None, description="Top-level error message if the task ultimately failed."
    )

    # Timestamps
    created_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: datetime | None = Field(default=None)


# ---------------------------------------------------------------------------
# API schemas
# ---------------------------------------------------------------------------


class TaskRequest(BaseModel):
    """Incoming payload for the POST /tasks endpoint."""

    task: str = Field(
        ...,
        description="Natural language description of the task to execute.",
        min_length=5,
    )
    context: dict[str, Any] | None = Field(
        default_factory=dict,
        description="Optional initial context key-value pairs passed to the agent.",
    )


class TaskResponse(BaseModel):
    """Response returned from the POST /tasks and GET /tasks/{task_id} endpoints."""

    task_id: str = Field(..., description="Unique task identifier.")
    status: TaskStatus = Field(..., description="Current task status.")
    message: str = Field(..., description="Human-readable status message.")
    report: str | None = Field(
        default=None, description="Final report (only present when status=COMPLETED)."
    )
